import '../src/content/helpers/moment.spec.js'
import '../src/content/search.spec.js'
import '../src/content/utils/html-to-text.spec.js'
import '../src/content/utils/parse-template.spec.js'
import '../src/content/editors/editor-prosemirror.spec.js'
